name: Customer Project Workflow

on:
  push:
    paths:
      - 'project5_Customer_Analytics/**'
      - '.github/workflows/**'

jobs:
  run-ml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Filter requirements and install dependencies
        run: |
          grep -Ev "cudf|colabtools|\.tar\.gz|\.whl|googlecolab|kernel_gateway|cyipopt" project5_Customer_Analytics/requirements.txt > filtered-requirements.txt
          pip install -r filtered-requirements.txt

      - name: Run the app
        run: python project5_Customer_Analytics/app.py

